export const MAKE_MODELS: Record<string, string[]> = {
  Bentley: ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  BYD: ['Han', 'Tang', 'Song', 'Song Plus', 'Qin', 'Seal', 'Atto 3', 'Dolphin', 'Yuan', 'e2'],
  Jetour: ['X50', 'X70', 'X70 Plus', 'X90', 'X90 Plus', 'Dashing', 'T2', 'Traveller'],
  Lamborghini: ['Huracán', 'Aventador', 'Revuelto', 'Urus', 'Gallardo', 'Murciélago', 'Diablo', 'Countach'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Wraith', 'Dawn', 'Cullinan', 'Spectre'],
  Suzuki: ['Swift', 'Baleno', 'Ciaz', 'Dzire', 'Ertiga', 'Vitara', 'Grand Vitara', 'Jimny', 'S-Presso', 'Celerio', 'XL7'],
  Zeekr: ['001', '007', '009', 'X', '7X'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Giulietta', '4C'],
  'Aston Martin': ['Vantage', 'DB11', 'DB12', 'DBS', 'DBX', 'Rapide'],
  Avatr: ['11', '12', '07'],
  BAIC: ['X25', 'X35', 'X55', 'X7', 'BJ40'],
  Changan: ['Alsvin', 'Eado', 'CS35', 'CS55', 'CS75', 'CS85', 'CS95', 'UNI-T', 'UNI-K', 'Hunter'],
  Chery: ['Arrizo 5', 'Arrizo 6', 'Tiggo 2', 'Tiggo 3', 'Tiggo 4', 'Tiggo 5X', 'Tiggo 7', 'Tiggo 8'],
  Denza: ['D9', 'N7', 'N8', 'Z9'],
  Exeed: ['LX', 'TXL', 'VX', 'RX'],
  Ferrari: [
    'Roma', 'Portofino', 'California', '296', 'F8', 'SF90', '812', 'Purosangue',
    'FF', 'GTC4Lusso', 'F12', 'LaFerrari',
    '488', '458', '430', '360', '355', '348', '328', '308',
    'Testarossa', '550', '575M', '599',
    'Enzo', 'F40', 'F50', 'Dino 246'
  ],
  Fiat: ['500', '500X', 'Panda', 'Tipo', 'Doblo'],
  Geely: ['Coolray', 'Emgrand', 'Okavango', 'Tugella', 'Monjaro', 'Preface', 'Azkarra'],
  GWM: ['Poer', 'Cannon'],
  Haval: ['Jolion', 'H6', 'H9', 'Dargo', 'F7', 'Big Dog'],
  Hongqi: ['H5', 'H9', 'HS5', 'HS7', 'E-HS9'],
  Hummer: ['H1', 'H2', 'H3', 'EV'],
  Isuzu: ['D-Max', 'MU-X', 'Rodeo'],
  JAC: ['JS3', 'JS4', 'JS6', 'JS8', 'Sunray', 'T8'],
  Jaecoo: ['J7', 'J8'],
  Koenigsegg: ['Agera', 'Regera', 'Jesko', 'Gemera', 'CC850'],
  Lotus: ['Elise', 'Exige', 'Evora', 'Emira', 'Eletre'],
  Maserati: ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'GranCabrio', 'MC20'],
  McLaren: ['570S', '600LT', '720S', '750S', '765LT', 'GT', 'Artura', 'P1', 'Senna'],
  MG: ['MG3', 'MG5', 'MG6', 'ZS', 'HS', 'RX5', 'RX8', 'MG4 EV', 'Cyberster'],
  Opel: ['Corsa', 'Astra', 'Insignia', 'Grandland', 'Mokka'],
  Peugeot: ['208', '2008', '301', '308', '3008', '408', '508', '5008'],
  Polestar: ['1', '2', '3', '4'],
  Renault: ['Clio', 'Megane', 'Duster', 'Captur', 'Kadjar', 'Koleos', 'Talisman', 'Arkana'],
  ROX: ['Star01', 'Miles03', 'GT'],
  Skoda: ['Fabia', 'Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq'],
  Soueast: ['DX3', 'DX5', 'DX8', 'S07'],
  Tank: ['300', '400', '500', '700'],
  Xiaomi: ['SU7', 'YU7'],
  Acura: ['ILX', 'TLX', 'RLX', 'RDX', 'MDX'],
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'RS Q8'],
  BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8'],
  Buick: ['Encore', 'Envision', 'Enclave'],
  Cadillac: ['ATS', 'CTS', 'CT4', 'CT5', 'XT4', 'XT5', 'XT6', 'Escalade'],
  Chevrolet: ['Spark', 'Aveo', 'Cruze', 'Malibu', 'Impala', 'Camaro', 'Corvette', 'Trax', 'Trailblazer', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban', 'Silverado'],
  Chrysler: ['300', 'Pacifica'],
  Dodge: ['Charger', 'Challenger', 'Durango', 'Journey'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Taurus', 'Mustang', 'EcoSport', 'Escape', 'Edge', 'Explorer', 'Expedition', 'Everest', 'Ranger', 'F-150', 'Bronco'],
  GMC: ['Terrain', 'Acadia', 'Yukon', 'Sierra'],
  Genesis: ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  Honda: ['Civic', 'Accord', 'City', 'Jazz', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Ridgeline', 'BR-V'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Azera', 'Veloster', 'Venue', 'Kona', 'Tucson', 'Santa Fe', 'Palisade', 'Creta', 'i10', 'i20', 'i30', 'Staria'],
  Infiniti: ['G35', 'G37', 'Q30', 'Q50', 'Q60', 'Q70', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80', 'FX35/FX45'],
  Jaguar: ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
  Kia: ['Picanto', 'Rio', 'Cerato', 'K5', 'Stinger', 'Sportage', 'Sorento', 'Telluride', 'Soul', 'Seltos', 'Carnival', 'Niro'],
  'Land Rover': ['Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Discovery', 'Discovery Sport', 'Defender'],
  Lexus: ['ES', 'GS', 'IS', 'LS', 'LC', 'RC', 'NX', 'RX', 'GX', 'LX', 'UX', 'LFA'],
  Lincoln: ['MKZ', 'Nautilus', 'Aviator', 'Navigator', 'Corsair'],
  Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-9', 'CX-30', 'MX-5'],
  'Mercedes-Benz': ['A-Class', 'A45', 'B-Class', 'C-Class', 'C63', 'E-Class', 'E63', 'S-Class', 'S63', 'S65', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'G63', 'G65', 'SL', 'AMG GT'],
  Mini: ['Cooper', 'Cooper S', 'Clubman', 'Countryman'],
  Mitsubishi: ['Attrage', 'Lancer', 'Mirage', 'ASX', 'Eclipse Cross', 'Outlander', 'Pajero', 'Xpander'],
  Nissan: ['Micra', 'Altima', 'Sentra', 'Maxima', 'Sunny', 'Patrol', 'X-Trail', 'X-Terra', 'Kicks', 'Juke', 'Magnite', 'Rogue', 'Pathfinder', 'Armada', 'Navara', 'GT-R', 'Skyline', '350Z', '370Z', 'Z', 'Silvia', 'Murano'],
  Porsche: ['911', '718', 'Cayman', 'Boxster', 'Carrera GT', 'Panamera', 'Macan', 'Cayenne', 'Taycan'],
  Ram: ['1500', '2500', '3500'],
  Subaru: ['Impreza', 'Legacy', 'Outback', 'Forester', 'Crosstrek', 'WRX', 'BRZ'],
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck'],
  Toyota: ['Corolla', 'Camry', 'Yaris', 'Avalon', 'Prius', 'Land Cruiser', 'Land Cruiser Prado', 'Fortuner', 'Hilux', 'RAV4', 'Highlander', '4Runner', 'Sequoia', 'Tacoma', 'Tundra', 'Supra', '86', 'C-HR', 'Rush', 'Innova'],
  Volkswagen: ['Polo', 'Golf', 'Jetta', 'Passat', 'Arteon', 'T-Roc', 'Tiguan', 'Touareg', 'Atlas', 'ID.4'],
  Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90']
};
