export const MAKE_MODELS: Record<string, string[]> = {
  Acura: ['ILX', 'TLX', 'RLX', 'RDX', 'MDX'],
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron'],
  BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8'],
  Buick: ['Encore', 'Envision', 'Enclave'],
  Cadillac: ['ATS', 'CTS', 'CT4', 'CT5', 'XT4', 'XT5', 'XT6', 'Escalade'],
  Chevrolet: ['Spark', 'Aveo', 'Cruze', 'Malibu', 'Impala', 'Camaro', 'Corvette', 'Trax', 'Trailblazer', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban', 'Silverado'],
  Chrysler: ['300', 'Pacifica'],
  Dodge: ['Charger', 'Challenger', 'Durango', 'Journey'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Taurus', 'Mustang', 'EcoSport', 'Escape', 'Edge', 'Explorer', 'Expedition', 'Everest', 'Ranger', 'F-150', 'Bronco'],
  GMC: ['Terrain', 'Acadia', 'Yukon', 'Sierra'],
  Genesis: ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  Honda: ['Civic', 'Accord', 'City', 'Jazz', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Ridgeline', 'BR-V'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Azera', 'Veloster', 'Venue', 'Kona', 'Tucson', 'Santa Fe', 'Palisade', 'Creta', 'i10', 'i20', 'i30', 'Staria'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80'],
  Jaguar: ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
  Kia: ['Picanto', 'Rio', 'Cerato', 'K5', 'Stinger', 'Sportage', 'Sorento', 'Telluride', 'Soul', 'Seltos', 'Carnival', 'Niro'],
  'Land Rover': ['Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Discovery', 'Discovery Sport', 'Defender'],
  Lexus: ['ES', 'GS', 'IS', 'LS', 'LC', 'RC', 'NX', 'RX', 'GX', 'LX', 'UX'],
  Lincoln: ['MKZ', 'Nautilus', 'Aviator', 'Navigator', 'Corsair'],
  Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-9', 'CX-30', 'MX-5'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'SL', 'AMG GT', 'Maybach S-Class'],
  Mini: ['Cooper', 'Cooper S', 'Clubman', 'Countryman'],
  Mitsubishi: ['Attrage', 'Lancer', 'Mirage', 'ASX', 'Eclipse Cross', 'Outlander', 'Pajero', 'Xpander'],
  Nissan: ['Altima', 'Sentra', 'Maxima', 'Sunny', 'Patrol', 'X-Trail', 'Kicks', 'Juke', 'Pathfinder', 'Armada', 'Navara', 'GT-R', '370Z', 'Murano'],
  Porsche: ['911', 'Cayman', 'Boxster', 'Panamera', 'Macan', 'Cayenne', 'Taycan'],
  Ram: ['1500', '2500', '3500'],
  Subaru: ['Impreza', 'Legacy', 'Outback', 'Forester', 'Crosstrek', 'WRX', 'BRZ'],
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck'],
  Toyota: ['Corolla', 'Camry', 'Yaris', 'Avalon', 'Prius', 'Land Cruiser', 'Land Cruiser Prado', 'Fortuner', 'Hilux', 'RAV4', 'Highlander', '4Runner', 'Sequoia', 'Tacoma', 'Tundra', 'Supra', 'C-HR', 'Rush', 'Innova'],
  Volkswagen: ['Polo', 'Golf', 'Jetta', 'Passat', 'Arteon', 'T-Roc', 'Tiguan', 'Touareg', 'Atlas', 'ID.4'],
  Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90']
};
