export type CountryCode = { name: string; dial: string; iso: string };

export const COUNTRY_CODES: CountryCode[] = [
  { name: 'United Arab Emirates', dial: '+971', iso: 'AE' },
  { name: 'Saudi Arabia', dial: '+966', iso: 'SA' },
  { name: 'Qatar', dial: '+974', iso: 'QA' },
  { name: 'Kuwait', dial: '+965', iso: 'KW' },
  { name: 'Bahrain', dial: '+973', iso: 'BH' },
  { name: 'Oman', dial: '+968', iso: 'OM' },
  { name: 'Egypt', dial: '+20', iso: 'EG' },
  { name: 'Jordan', dial: '+962', iso: 'JO' },
  { name: 'Lebanon', dial: '+961', iso: 'LB' },
  { name: 'India', dial: '+91', iso: 'IN' },
  { name: 'Pakistan', dial: '+92', iso: 'PK' },
  { name: 'Philippines', dial: '+63', iso: 'PH' },
  { name: 'Bangladesh', dial: '+880', iso: 'BD' },
  { name: 'Sri Lanka', dial: '+94', iso: 'LK' },
  { name: 'Nepal', dial: '+977', iso: 'NP' },
  { name: 'United Kingdom', dial: '+44', iso: 'GB' },
  { name: 'United States', dial: '+1', iso: 'US' },
  { name: 'Canada', dial: '+1', iso: 'CA' },
  { name: 'Germany', dial: '+49', iso: 'DE' },
  { name: 'France', dial: '+33', iso: 'FR' },
  { name: 'Italy', dial: '+39', iso: 'IT' },
  { name: 'Spain', dial: '+34', iso: 'ES' },
  { name: 'Netherlands', dial: '+31', iso: 'NL' },
  { name: 'Russia', dial: '+7', iso: 'RU' },
  { name: 'Turkey', dial: '+90', iso: 'TR' },
  { name: 'China', dial: '+86', iso: 'CN' },
  { name: 'Japan', dial: '+81', iso: 'JP' },
  { name: 'South Korea', dial: '+82', iso: 'KR' },
  { name: 'Australia', dial: '+61', iso: 'AU' },
  { name: 'South Africa', dial: '+27', iso: 'ZA' },
  { name: 'Nigeria', dial: '+234', iso: 'NG' },
  { name: 'Kenya', dial: '+254', iso: 'KE' },
  { name: 'Morocco', dial: '+212', iso: 'MA' },
  { name: 'Iran', dial: '+98', iso: 'IR' },
  { name: 'Indonesia', dial: '+62', iso: 'ID' },
  { name: 'Malaysia', dial: '+60', iso: 'MY' },
  { name: 'Singapore', dial: '+65', iso: 'SG' },
  { name: 'Brazil', dial: '+55', iso: 'BR' }
];
