export const SPECIFICATIONS = ['GCC', 'American', 'Japanese', 'Korean', 'European', 'Canadian', 'Chinese', 'Other'];
export const DRIVETRAINS = ['FWD', 'RWD', 'AWD', '4WD'];
export const FUEL_TYPES = ['Gasoline', 'Diesel', 'Hybrid', 'Plug-in Hybrid', 'Electric'];
export const ENGINES = ['I3', 'I4', 'I5', 'I6', 'V6', 'V8', 'V10', 'V12', 'V16', 'W16', 'Electric (no engine)'];
export const TRANSMISSIONS = ['Automatic', 'Manual'];
export const SEAT_OPTIONS = [2, 3, 4, 5, 6];
export const EXTERIOR_COLORS = ['White', 'Black', 'Silver', 'Gray', 'Red', 'Blue', 'Green', 'Yellow', 'Gold', 'Beige', 'Brown', 'Orange', 'Bronze', 'Pink', 'Other'];
export const INTERIOR_COLORS = ['Black', 'Beige/Tan', 'Brown', 'Gray', 'Red', 'White', 'Blue', 'Green', 'Yellow', 'Orange', 'Other'];
export const HORSEPOWER_RANGES = ['0-150 bhp', '151-250 bhp', '251-350 bhp', '350-450 bhp', '451+ bhp'];
